// QUICK EDIT: change all three links here.
function getProjectLinks(){return{contractAddress:"PASTE_CA_HERE",pumpFun:"https://pump.fun/coin/PASTE_CA_HERE",twitter:"https://x.com/PASTE_USERNAME_HERE"}}
import * as THREE from "three";import{GLTFLoader}from"three/addons/loaders/GLTFLoader.js";import{OrbitControls}from"three/addons/controls/OrbitControls.js";
const links=getProjectLinks();pumpLink().href=links.pumpFun;document.querySelector("#twitter-link").href=links.twitter;function pumpLink(){return document.querySelector("#pump-link")}document.querySelector("#copy-ca").onclick=async e=>{await navigator.clipboard.writeText(links.contractAddress);e.currentTarget.textContent="[ COPIED! ]";setTimeout(()=>e.currentTarget.textContent="[ COPY CA ]",1200)};
const grid=document.querySelector("#meme-grid"),modal=document.querySelector("#modal"),preview=document.querySelector("#preview");for(let i=1;i<=14;i++){const img=new Image;img.src=`assets/memes/${i}.jpg`;img.alt=`Cold Caller meme ${i}`;img.loading="lazy";img.onclick=()=>{preview.src=img.src;modal.classList.add("on")};grid.append(img)}document.querySelector("#close").onclick=()=>modal.classList.remove("on");modal.onclick=e=>{if(e.target===modal)modal.classList.remove("on")};document.querySelector("#visitors").textContent=String(Math.floor(Math.random()*999999)).padStart(6,"0");
const canvas=document.querySelector("#model-canvas"),stage=document.querySelector(".stage"),scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(28,1,.1,1000);camera.position.set(0,.7,8);const renderer=new THREE.WebGLRenderer({canvas,alpha:true,antialias:false});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=THREE.SRGBColorSpace;const controls=new OrbitControls(camera,canvas);controls.enableDamping=true;controls.enablePan=false;controls.minDistance=3;controls.maxDistance=12;controls.autoRotate=true;controls.autoRotateSpeed=15;controls.target.set(0,.5,0);scene.add(new THREE.HemisphereLight(0x80dfff,0x000044,4));const light=new THREE.DirectionalLight(0xffffff,4);light.position.set(4,7,5);scene.add(light);let model,chaos=0,baseScale=1;
new GLTFLoader().load("assets/coldcaller.glb",gltf=>{const obj=gltf.scene;model=obj;const box=new THREE.Box3().setFromObject(obj),size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3());obj.position.sub(center);
                                                    
                                                     
baseScale = 4 / Math.max(size.x, size.y, size.z);
obj.scale.setScalar(baseScale);
obj.position.y = 1;


                                                     
                                                     obj.traverse(c=>{if(c.isMesh){c.material=c.material.clone();c.material.flatShading=true;c.material.needsUpdate=true}});scene.add(obj);document.querySelector("#loading").remove()},undefined,()=>document.querySelector("#loading").textContent="coldcaller.glb NOT FOUND");
document.querySelector("#freeze").onclick=()=>{chaos=1;const ice=document.querySelector("#ice");ice.classList.add("on");setTimeout(()=>ice.classList.remove("on"),900)};function resize(){const r=stage.getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix()}addEventListener("resize",resize);resize();const clock=new THREE.Clock;function loop(){const t=clock.getElapsedTime();chaos*=.94;if(model){model.rotation.z=Math.sin(t*3)*.08+Math.sin(t*35)*chaos*.35;model.rotation.x=Math.sin(t*27)*chaos*.25;model.scale.set(baseScale*(1+Math.sin(t*18)*chaos*.35),baseScale*(1+Math.cos(t*23)*chaos*.25),baseScale)}controls.autoRotateSpeed=15+chaos*45;controls.update();renderer.render(scene,camera);requestAnimationFrame(loop)}loop();
